### PR TITLE
Design 

### PR DESCRIPTION
**Pull request by RazanTayyem**

### CODE REVIEW

**Review by jema28 — CHANGES_REQUESTED** [review]
The page errors: 

screenshot 2018-12-06 at 11 24 25

Please also delete the binary files that aren't being used.

**Comment by jema28** [comment]
The course isn't showing up on the page. Please fix this also @RazanTayyem @mhmdtshref.

**Review by jema28 — APPROVED** [review]
Please delete the images first and then ready to merge.

**Review by mhmdtshref — COMMENTED** [review]
Should remove the unneeded images in the `public/img` folder.

**Review by jema28 — APPROVED** [review]

**Review by mhmdtshref — APPROVED** [review]
images removed, Done!

**Pull request merged**
